In [2]:
# A simple tensorflow program with tensorboard
import os
import tensorflow as tf

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
writer.close()

5


In [3]:
# Explicitly naming variables in tensorboard graphs

a = tf.constant(2, name ='a')
b = tf.constant(3, name ='b')
x = tf.add(a, b, name='add')

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))

5


In [4]:
# Contants

a = tf.constant([2,2], name='a')
b = tf.constant([[0,1],[2,3]], name = 'b')
x = tf.multiply(a,b, name='mul')

with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


In [6]:
# Tensors Filled with a specific value

y = tf.zeros([2,3], tf.int32)

In [7]:
# Tensors filled with a specific value, similar to numpy.zeros_like 

x = tf.zeros_like(y)
with tf.Session() as sess:
    print(sess.run(x))

[[0 0 0]
 [0 0 0]]


In [8]:
# Some more tensors with a specific value like numpy

specific_tensor = tf.ones([2,3],tf.int32)

specific_tensor_like = tf.ones_like(specific_tensor)

with tf.Session() as sess:
    print(sess.run(specific_tensor_like))

[[1 1 1]
 [1 1 1]]


In [9]:
# Tensors filled with a specific value like NumPy.full

specific_tensor_any = tf.fill([2,3],8)

with tf.Session() as sess:
    print(sess.run(specific_tensor_any))

[[8 8 8]
 [8 8 8]]


In [12]:
# Constants as sequences

lin_spaces = tf.lin_space(10.0,13.0,6)
tf_range = tf.range(3,18,3)
tf_range_default = tf.range(5)

with tf.Session() as sess:
    print(sess.run(lin_spaces))
    print(sess.run(tf_range))
    print(sess.run(tf_range_default))
    
# NOT the same as Numpy Sequences
# Tensor objects are not iterable
# for _ in tf.range(4): #TypeError

[ 10.          10.60000038  11.19999981  11.80000019  12.39999962  13.        ]
[ 3  6  9 12 15]
[0 1 2 3 4]


Randomly Generated Constants


tf.random_normal

tf.truncated_normal

tf.random_uniform

tf.random_shuffle

tf.random_crop

tf.multinomial

tf.random_gamma


In [8]:
# Randomaly generated constants

tf.set_random_seed(1234)

# Need to read more about this ???

In [9]:
# Read Operations slide from the slide note. Slide number : 25

In [10]:
# Arithmetic Ops similar to numpy

abs1 = tf.abs(2)
neg = tf.negative(5)

print(sess.run([abs1, neg]))

[2, -5]


In [12]:
# Wizard of Div

a = tf.constant([2,2], name='a')
b = tf.constant([[0,1],[2,3]],name='b')

print(sess.run(tf.div(b,a)))
print(sess.run(tf.divide(b,a)))

# There are lot of others type of divide, which we can check.

[[0 0]
 [1 1]]
[[ 0.   0.5]
 [ 1.   1.5]]


In [19]:
# Tensorflow takes python natives types: boolean, numeric(int, float), strings

# Scalars are treated like 0-d tensors

t_0 = 19
print(sess.run(tf.zeros_like(t_0)))
print(sess.run(tf.ones_like(t_0)))

# b in front makes it bytes literal
t_1 = [b"apple",b"peach",b"grape"]
print(t_1)
print(sess.run(tf.zeros_like(t_1)))


t_2 = [[True, False, False],
       [False,False,True],
       [False,True,False]]

print(sess.run(tf.ones_like(t_2)))
print(sess.run(tf.zeros_like(t_2)))

0
1
[b'apple', b'peach', b'grape']
[b'' b'' b'']
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


In [22]:
# Tensorflow integrates seamlessly with NumPy

# For tf.Session.run(fetches): if the requested fetch is a tensor, output will be a NumPy ndarray.
import numpy as np

a = tf.zeros([2,3], np.int32)
print(type(a))

b = sess.run(a)
print(type(b))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


In [23]:
# Print out the graph def

my_const = tf.constant([1.0,2.0], name="my_const")

print(sess.graph.as_graph_def())

# Constants makes loading graphs expensive when they are big. As a thumb rule, we should only
# use constants for primitive types.

# We should use variables or readers for more data that requires more memory.

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Const_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_3"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT

In [29]:
# Variables

s = tf.Variable(2, name="scalar")
m = tf.Variable([[0,1],[2,3]], name="matrix")
w = tf.Variable(tf.zeros([784,10]))

# create varaibles with tf.get_variable

# s_get = tf.get_variable("scalar_get", initializer=tf.constant(2))
# m_get = tf.get_variable("matrix_get", initializer=tf.constant([[0,1],[2,3]]))
# w_get = tf.get_variable("big_matrix_get", shape=(784,10), initializer = tf.zeros_initializer())

# Initialize only a subset of variables
# sess.run(tf.variables_initializer([a,b]))

# Initialize a single variable
sess.run(w.initializer)
print(w)

<tf.Variable 'Variable_5:0' shape=(784, 10) dtype=float32_ref>


In [31]:
# Eval a variable

w = tf.Variable(tf.truncated_normal([700,10]))
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())

[[-1.72831786  1.14954269  1.94494307 ...,  0.78394353 -0.28414121
  -1.00032794]
 [ 0.05107353 -1.07789004 -1.40605223 ...,  0.48239845  0.4291659
   0.96946239]
 [-0.43083116  0.3363086   0.55636716 ..., -0.0549511   1.66441095
  -1.15616381]
 ..., 
 [-0.12081058 -1.91476202  0.49617484 ..., -0.13954742  0.49001756
  -1.55163884]
 [-0.56380677  0.46374005  0.39819387 ...,  1.70508981 -0.34309828
   1.8094157 ]
 [ 1.18768835  0.1648322   0.45599633 ..., -0.66064614  0.17884301
  -0.93751699]]


In [6]:
# tf.Variable.assign()

w = tf.Variable(10)
v = tf.Variable(2)
v_assign = v.assign(2 * v)
assign_op = w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    sess.run(assign_op)
    sess.run(v.initializer)
    sess.run(v_assign)
    print(sess.run(v_assign))
    print(sess.run(v_assign))
    print(w.eval())

8
16
100


In [5]:
# tf.Variable.assign()

# create a variable whose intial vale is 2 
my_var = tf.Variable(2, name="my_var")

#assign a*2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two))

4
8


In [9]:
# assign_add() and assign_sub()

my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    
    print(sess.run(my_var.assign_add(10)))
    
    print(sess.run(my_var.assign_sub(2)))

20
18


In [11]:
# Each Session maintains its own copy of variables

W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

sess1.close()
sess2.close()

20
8


In [14]:
# Control Dependencies 
# TODO Need to read this part 

a = tf.constant(5)
b = tf.constant(6)
c = tf.multiply(a,b)
d = tf.add(a,b)
e = tf.subtract(a,b)

g = tf.get_default_graph()

with g.control_dependencies([a,b,c]):
    sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
    print(sess.run(c))
    print(sess.run(d))   
    sess.close()

30
11


In [6]:
# Placeholders
# tf.placeholder(dtype, shape=None, name=None)

# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=[3])

b = tf.constant([5,5,5], tf.float32)

c = a + b

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a: [1,2,3]}))

[6. 7. 8.]


In [7]:
# Feeding values to TF ops
# Helpful for testing

a = tf.add(3,5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    print(sess.run(b, feed_dict={a : 15}))

45


In [2]:
# Normal Loading

x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x,y)

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(z)

writer.close()


In [1]:
# Lazy Loading
import tensorflow as tf
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

writer = tf.summary.FileWriter('./graphs/lazy_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(tf.add(x,y,name='lazy_add'))

writer.close()

In Lazy Loading "Add" added 20 times to graph definition.

Solution:
1. Separate definition of ops from computing/running ops
2. Use Python property to ensure function is also loaded once the first time it is called.

So we should avoid lazy loading.

In [ ]:
import tensorflow as tf
sess1 = tf.InteractiveSession()
a = tf.constant(5.0)
print(a.eval())
tf.InteractiveSession().close()
sess.close()

5.0


C:\Users\m.kumar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
